import { indexedPrefix, lastIndex } from "./index-bounds.js";
import {
  quoteProperty,
  toCamelCase,
  toPascalCase,
  toTypeName,
  UniqueNames,
} from "./naming.js";
import type { PveCall, PveMethod, PveNode, PveSchema } from "./schema.js";
import { isOptional, pathVariable } from "./schema.js";

const INDENT = "  ";
const METHOD_ORDER: PveMethod[] = ["GET", "POST", "PUT", "DELETE"];
/** Width at which a union is broken across lines. */
const UNION_WRAP = 76;

export interface ModelMeta {
  source: string;
  sha256: string;
}

const LICENCE = `// Proxmox-API Interactive proxmox API for developpers how do not like reading docs
// Copyright (C) 2020-2024  Chemouni Uriel <uchemouni@gmail.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.`;

function pad(depth: number): string {
  return INDENT.repeat(depth);
}

/**
 * Make text safe inside a block comment. `*​/` would end the comment early and
 * braces are TSDoc syntax, so both are escaped.
 */
function escapeDoc(text: string): string {
  return text.replace(/\*\//g, "*\\/").replace(/([{}])/g, "\\$1");
}

function docBlock(lines: string[], depth: number): string[] {
  if (lines.length === 0) return [];
  const p = pad(depth);
  if (lines.length === 1)
    return [`${p}/** ${escapeDoc(lines[0] as string)} */`];
  return [
    `${p}/**`,
    ...lines.map((line) => `${p} * ${escapeDoc(line)}`.trimEnd()),
    `${p} */`,
  ];
}

function splitLines(text: string): string[] {
  return text
    .split(/[\r\n]+/)
    .map((line) => line.trim())
    .filter(Boolean);
}

/** Join a rendered union onto its declaration without a trailing space. */
function indentUnion(rendered: string): string {
  return rendered.startsWith("\n") ? rendered : ` ${rendered}`;
}

function union(members: string[], depth: number): string {
  const unique = [...new Set(members)];
  if (unique.length === 1) return unique[0] as string;
  const flat = unique.join(" | ");
  if (flat.length <= UNION_WRAP && !flat.includes("\n")) return flat;
  const p = pad(depth + 1);
  return `\n${unique.map((m) => `${p}| ${m}`).join("\n")}`;
}

export class ModelEmitter {
  private readonly names = new UniqueNames(["Api", "Proxmox"]);
  /** Canonical schema key -> alias name, so identical types share a name. */
  private readonly aliasByKey = new Map<string, string>();
  private readonly aliasDecls = new Map<string, string[]>();
  private readonly returnDecls = new Map<string, string[]>();
  private readonly api: string[] = [];
  private callCount = 0;
  /** Indexed prefixes with no catalogued bound, reported after the run. */
  readonly unboundedPrefixes = new Set<string>();

  constructor(
    private readonly nodes: PveNode[],
    private readonly meta: ModelMeta,
  ) {}

  build(): string {
    this.api.push(`${pad(1)}export interface Api {`);
    for (const node of this.nodes) this.emitNode(node, 2, new Set());
    this.api.push(`${pad(1)}}`);

    const sorted = <T>(map: Map<string, T[]>): string[] =>
      [...map.keys()].sort().flatMap((key) => map.get(key) as string[]);

    return [
      LICENCE,
      "",
      "// Generated by @virtbase/proxmox-api-generator - do not edit by hand.",
      "// Regenerate with `bun run codegen`.",
      `// Source:  ${this.meta.source}`,
      `// SHA-256: ${this.meta.sha256}`,
      `// Covers ${this.callCount} operations.`,
      "",
      "export namespace Proxmox {",
      ...sorted(this.aliasDecls),
      ...sorted(this.returnDecls),
      ...this.api,
      "}",
      "",
      "export default Proxmox;",
      "",
    ].join("\n");
  }

  // ---------------------------------------------------------------- api tree

  private emitNode(node: PveNode, depth: number, pathVars: Set<string>): void {
    const p = pad(depth);
    const variable = pathVariable(node.text);
    let scope = pathVars;

    if (variable) {
      const argument = toCamelCase(variable) || "value";
      this.api.push(
        `${p}$(${argument}: ${this.pathVariableType(node, variable)}): {`,
      );
      scope = new Set([...pathVars, variable]);
    } else {
      this.api.push(`${p}${quoteProperty(node.text)}: {`);
    }

    for (const method of METHOD_ORDER) {
      const call = node.info?.[method];
      if (call) this.emitCall(node, call, method, depth + 1, scope);
    }
    for (const child of node.children ?? []) {
      this.emitNode(child, depth + 1, scope);
    }
    this.api.push(`${p}};`);
  }

  /**
   * `{vmid}` is an integer and `{node}` a string; take the answer from the
   * call's own parameter declaration rather than a list of special cases.
   */
  private pathVariableType(node: PveNode, variable: string): string {
    for (const method of METHOD_ORDER) {
      const declared = node.info?.[method]?.parameters?.properties?.[variable];
      if (!declared) continue;
      if (declared.type === "integer" || declared.type === "number") {
        return "number";
      }
      if (declared.type === "string") return "string";
    }
    return "string";
  }

  private emitCall(
    node: PveNode,
    call: PveCall,
    method: PveMethod,
    depth: number,
    pathVars: Set<string>,
  ): void {
    this.callCount++;
    const p = pad(depth);
    const doc: string[] = [];
    if (call.description) doc.push(...splitLines(call.description));
    doc.push(`${method} ${node.path}`);
    if (call.allowtoken !== undefined)
      doc.push(`@allowtoken ${call.allowtoken}`);
    if (call.download_allowed) doc.push("@downloadAllowed 1");
    if (call.permissions !== undefined) {
      doc.push(`@permissions ${JSON.stringify(call.permissions)}`);
    }
    this.api.push(...docBlock(doc, depth));

    const parameter = this.parameterType(call, pathVars, depth);
    const returns = this.returnType(node, call, method);
    this.api.push(
      `${p}$${method.toLowerCase()}(${parameter}): Promise<${returns}>;`,
    );
  }

  // --------------------------------------------------------------- parameters

  private parameterType(
    call: PveCall,
    pathVars: Set<string>,
    depth: number,
  ): string {
    const properties = call.parameters?.properties ?? {};
    const entries = Object.entries(properties).filter(
      ([name]) => !pathVars.has(name),
    );
    if (entries.length === 0) return "";

    const body = this.objectBody(
      Object.fromEntries(entries),
      call.parameters?.additionalProperties,
      depth,
    );
    const allOptional = entries.every(([, schema]) => isOptional(schema));
    return `param${allOptional ? "?" : ""}: ${body}`;
  }

  // -------------------------------------------------------------- return types

  private returnType(node: PveNode, call: PveCall, method: PveMethod): string {
    const returns = call.returns;
    if (!returns || returns.type === "null") return "null";

    const structured =
      returns.type === "object" ||
      (returns.type === "array" && returns.items?.type === "object") ||
      (!returns.type && returns.properties !== undefined);
    if (!structured) {
      return this.typeExpr(returns, 1, `${node.path} ${call.name}`);
    }

    const target =
      returns.type === "array" ? (returns.items as PveSchema) : returns;
    const body = this.objectBody(
      target.properties ?? {},
      // Upstream forced an index signature onto every returned object
      // (`additionalProperties || 1`), which silently made each one accept
      // any key. Honour what the schema actually says.
      target.additionalProperties ?? returns.additionalProperties,
      1,
    );
    if (body === "any" || body === "Record<string, any>") {
      return returns.type === "array" ? `${body}[]` : body;
    }

    const name = this.names.claim(this.returnTypeName(node, call));
    this.returnDecls.set(name, [
      ...docBlock([`Returned by ${method} ${node.path}`], 1),
      `${pad(1)}export interface ${name} ${body}`,
    ]);
    return returns.type === "array" ? `${name}[]` : name;
  }

  private returnTypeName(node: PveNode, call: PveCall): string {
    const segments = node.path
      .split("/")
      .filter((segment) => segment && !segment.startsWith("{"));
    const base = toCamelCase([...segments, call.name].join(" "));
    return base || "response";
  }

  // -------------------------------------------------------------- type mapping

  private typeExpr(schema: PveSchema, depth: number, hint: string): string {
    if (schema.oneOf?.length) {
      return union(
        schema.oneOf.map((variant) => this.typeExpr(variant, depth, hint)),
        depth,
      );
    }

    switch (schema.type) {
      case "boolean":
        return "boolean";
      case "integer":
      case "number":
        return "number";
      case "null":
        return "null";
      case "any":
        return "any";
      case "array":
        return this.arrayExpr(schema, depth, hint);
      case "object":
        return this.objectBody(
          schema.properties ?? {},
          schema.additionalProperties,
          depth,
        );
      case "string":
        return this.stringExpr(schema, hint);
      default:
        // No `type`: infer from whichever sibling keyword is present.
        if (schema.enum) return this.enumAlias(schema.enum, hint);
        if (schema.properties) {
          return this.objectBody(
            schema.properties,
            schema.additionalProperties,
            depth,
          );
        }
        if (schema.items) return this.arrayExpr(schema, depth, hint);
        return "any";
    }
  }

  private stringExpr(schema: PveSchema, hint: string): string {
    if (schema.enum) return this.enumAlias(schema.enum, hint);
    if (typeof schema.format === "string")
      return this.formatAlias(schema.format);
    return "string";
  }

  private arrayExpr(schema: PveSchema, depth: number, hint: string): string {
    if (!schema.items) return "any[]";
    const element = this.typeExpr(schema.items, depth, hint);
    // `A | B[]` would parse as `A | (B[])`, so wrap anything with a union.
    return element.includes("|") ? `Array<${element}>` : `${element}[]`;
  }

  /**
   * Render an object type. Properties spelled `net[n]` become a pattern index
   * signature covering every index PVE accepts, rather than the hand-picked
   * `net0`..`net3` upstream expanded them to.
   */
  private objectBody(
    properties: Record<string, PveSchema>,
    additional: PveSchema["additionalProperties"],
    depth: number,
  ): string {
    const lines: string[] = [];
    const inner = depth + 1;
    const p = pad(inner);

    for (const [name, schema] of Object.entries(properties)) {
      const indexed = indexedPrefix(name);
      if (indexed) {
        lines.push(...this.indexedSlots(indexed, schema, inner));
        continue;
      }
      lines.push(...docBlock(this.describe(schema, name), inner));
      const optional = isOptional(schema) ? "?" : "";
      lines.push(
        `${p}${quoteProperty(name)}${optional}: ${this.typeExpr(schema, inner, name)};`,
      );
    }

    if (additional && typeof additional === "object") {
      lines.push(...docBlock(["Additional, unlisted properties."], inner));
      lines.push(
        `${p}[key: string]: ${this.typeExpr(additional, inner, "value")};`,
      );
    } else if (additional === 1 || additional === "1") {
      lines.push(...docBlock(["Additional, unlisted properties."], inner));
      lines.push(`${p}[key: string]: any;`);
    }

    if (lines.length === 0) return "Record<string, any>";
    return ["{", ...lines, `${pad(depth)}}`].join("\n");
  }

  /**
   * Expand an indexed property into the slots PVE actually accepts.
   *
   * `scsi[n]` becomes `scsi0?` through `scsi30?` rather than an unbounded
   * `` [key: `scsi${number}`] ``, which would have accepted `scsi99`. The
   * documentation is hoisted onto a named alias so each of the 31 keys shows
   * it on hover without repeating it 31 times in the file.
   */
  private indexedSlots(
    prefix: string,
    schema: PveSchema,
    depth: number,
  ): string[] {
    const p = pad(depth);
    const doc = this.describe(schema, `${prefix}[n]`);
    const bound = lastIndex(prefix);

    if (bound === undefined) {
      // Unknown prefix: stay permissive rather than inventing a limit.
      this.unboundedPrefixes.add(prefix);
      return [
        ...docBlock(doc, depth),
        `${p}[key: \`${prefix}\${number}\`]: ${this.typeExpr(schema, depth, prefix)};`,
      ];
    }

    const type = this.slotAlias(prefix, schema, doc, depth);
    const lines: string[] = [];
    for (let index = 0; index <= bound; index++) {
      lines.push(`${p}${prefix}${index}?: ${type};`);
    }
    return lines;
  }

  /**
   * The value type for one indexed property, as a documented alias when the
   * type would otherwise be a bare primitive.
   */
  private slotAlias(
    prefix: string,
    schema: PveSchema,
    doc: string[],
    depth: number,
  ): string {
    const rendered = this.typeExpr(schema, depth, prefix);
    // Anything already named or structural carries its own documentation.
    if (!["string", "number", "boolean", "any"].includes(rendered)) {
      return rendered;
    }

    const key = `slot:${rendered}:${JSON.stringify(schema)}`;
    const existing = this.aliasByKey.get(key);
    if (existing) return existing;

    const name = this.names.claim(toPascalCase(prefix) || "Slot");
    this.aliasByKey.set(key, name);
    this.aliasDecls.set(name, [
      ...docBlock(doc, 1),
      `${pad(1)}export type ${name} = ${rendered};`,
    ]);
    return name;
  }

  /** The JSDoc lines for one property: prose first, then constraints. */
  private describe(schema: PveSchema, name: string): string[] {
    const doc: string[] = [];
    const prose = schema.verbose_description ?? schema.description;
    if (prose) doc.push(...splitLines(prose));
    if (name.endsWith("[n]")) {
      doc.push(
        `Indexed property: \`${name.slice(0, -3)}0\`, \`${name.slice(0, -3)}1\`, ...`,
      );
    }

    for (const key of [
      "format_description",
      "pattern",
      "minimum",
      "maximum",
      "minLength",
      "maxLength",
      "default",
    ] as const) {
      const value = schema[key];
      if (value === undefined) continue;
      doc.push(
        `@${key} ${typeof value === "string" ? value : JSON.stringify(value)}`,
      );
    }
    if (typeof schema.format === "string") doc.push(`@format ${schema.format}`);
    if (typeof schema.format === "object") {
      // A property string: the value packs these fields as `k=v,k=v`.
      const fields = Object.entries(schema.format)
        .map(([field, spec]) => `${field}=<${spec.type ?? "string"}>`)
        .join(", ");
      doc.push(`@propertyString ${fields}`);
    }
    if (schema.typetext) doc.push(`@typetext ${schema.typetext}`);
    if (schema.requires) doc.push(`@requires ${schema.requires}`);
    if (schema["type-property"]) {
      // TypeScript cannot make one property's type depend on a sibling, so
      // the union is widened and the rule recorded here instead.
      const variants = (schema.oneOf ?? [])
        .map((v) => (v["instance-types"] ?? []).join("|"))
        .filter(Boolean)
        .join(", ");
      doc.push(
        `@discriminatedBy ${schema["type-property"]}${variants ? ` (${variants})` : ""}`,
      );
    }
    return doc;
  }

  // ------------------------------------------------------------ named aliases

  /** `pve-vmid` -> `export type PveVmid = string;`, shared across every use. */
  private formatAlias(format: string): string {
    const key = `format:${format}`;
    const existing = this.aliasByKey.get(key);
    if (existing) return existing;

    const candidate = toTypeName(format, "");
    if (!candidate) return "string";

    const name = this.names.claim(candidate);
    this.aliasByKey.set(key, name);
    this.aliasDecls.set(name, [
      ...docBlock([`PVE format \`${format}\`.`], 1),
      `${pad(1)}export type ${name} = string;`,
    ]);
    return name;
  }

  /** Enumerations become real unions, deduplicated by their value set. */
  private enumAlias(values: string[], hint: string): string {
    const key = `enum:${JSON.stringify([...values].sort())}`;
    const existing = this.aliasByKey.get(key);
    if (existing) return existing;

    const name = this.names.claim(
      toTypeName(hint.split(/[\s/]/).filter(Boolean).pop() ?? "", "Enum") ||
        "Enum",
    );
    this.aliasByKey.set(key, name);
    const members = values.map((value) => JSON.stringify(value));
    this.aliasDecls.set(name, [
      `${pad(1)}export type ${name} =${indentUnion(union(members, 1))};`,
    ]);
    return name;
  }
}

export interface EmitResult {
  code: string;
  /**
   * Indexed prefixes emitted without a bound. Non-empty means Proxmox has
   * added an indexed property that `INDEX_BOUNDS` does not know about.
   */
  unboundedPrefixes: string[];
}

export function emitModel(nodes: PveNode[], meta: ModelMeta): EmitResult {
  const emitter = new ModelEmitter(nodes, meta);
  const code = emitter.build();
  return { code, unboundedPrefixes: [...emitter.unboundedPrefixes].sort() };
}
